export const louieSlides = [
    {
        id: 'slide25',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/louiefamily1.jpg'),
        alt: 'Louie Wee Lee',
        citation: '',
        img2: require('../../images/louie/louiefamily2.jpg'),
        alt2:'Louie family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide26',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/louiefamily4.jpg'),
        alt: 'Louie Wee Lee',
        citation: '',
        img2: require('../../images/louie/louiefamily3.jpg'),
        alt2:'Louie family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide27',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/wedding1.jpg'),
        alt: 'Louie Wee Lee',
        citation: '',
        img2: require('../../images/louie/louiefamily5.jpg'),
        alt2:'Louie family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide28',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/wedding2.jpg'),
        alt: 'Beach',
        citation: '',
        img2: require('../../images/louie/wedding3.jpg'),
        alt2:'Wedding',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide29',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/beach.jpg'),
        alt: 'Beach',
        citation: '',
        img2: require('../../images/louie/louiefamily6.jpg'),
        alt2:'Wedding',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide30',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/cakecutting.jpg'),
        alt: 'Cake Cutting',
        citation: '',
        img2: require('../../images/louie/christmas.jpg'),
        alt2:'Christmas',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide31',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/robertlouie1.jpg'),
        alt: 'Robert Louie',
        citation: '',
        img2: require('../../images/louie/robertlouie2.jpg'),
        alt2:'Christmas',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide32',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/louiefamily7.jpg'),
        alt: 'Louie family',
        citation: '',
        img2: require('../../images/louie/louiefamily8.jpg'),
        alt2:'Christmas',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide33',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/nevada.jpg'),
        alt: 'Nevada Stateline',
        citation: '',
        img2: require('../../images/louie/mahjong.jpg'),
        alt2:'mahjong',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide34',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/baby.jpg'),
        alt: 'Baby',
        citation: '',
        img2: require('../../images/louie/kids.jpg'),
        alt2:'kids',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide35',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/timothychang.jpg'),
        alt: 'Timothy Chang',
        citation: '',
        img2: require('../../images/louie/charlie.jpeg'),
        alt2:'Louie Family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide36',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/graduate.jpg'),
        alt: 'Timothy Chang',
        citation: '',
        img2: require('../../images/louie/louiefamily9.jpg'),
        alt2:'Louie Family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide37',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/louiefamily10.jpg'),
        alt: 'Louie Family',
        citation: '',
        img2: require('../../images/louie/louiefamily9.jpg'),
        alt2:'Louie Family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide38',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/louiefamily11.jpg'),
        alt: 'Louie Family',
        citation: '',
        img2: require('../../images/louie/louiefamily12.jpg'),
        alt2:'Louie Family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    },
    {
        id: 'slide39',
        addImg: true,
        lightText: true,
        lightTextDesc: true,
        topLine: 'The Louie Family',
        headline: '',
        description: '',
        img: require('../../images/louie/weelee.jpg'),
        alt: 'Louie Family',
        citation: '',
        img2: require('../../images/louie/louiefamily12.jpg'),
        alt2:'Louie Family',
        flex: true,
        citation2: '',
        dark: true,
        primary: true,
        darkText: false
    }
]